#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${SCRIPT_DIR}/lxd-abstract

if [ -d "${LXD_FOLDER}" ]; then
    showError "The asked containter already exits"
fi

showWarning "Create the container ${LXD_NAME}"

showMessage "Create Container"
sudo lxc launch images:debian/stretch ${LXD_NAME} > /dev/null
sleep 4

showMessage "Add entry in /etc/hosts"
LXD_IP=`sudo lxc list ${LXD_NAME} --format csv -c 4 | cut -d' ' -f1`
sudo sh -c "echo \"${LXD_IP} ${LXD_HOST} # Generated by lxd-deploy\" >> /etc/hosts"
sudo lxc exec ${LXD_NAME} -- sh -c "echo \"127.0.0.1 ${LXD_HOST} # Generated by lxd-deploy\" >> /etc/hosts"

showMessage "Upgrade default packages"
sudo lxc exec ${LXD_NAME} -- export DEBIAN_FRONTEND=noninteractive
sudo lxc exec ${LXD_NAME} -- apt-get -qq update          > /dev/null
sudo lxc exec ${LXD_NAME} -- apt-get -qq -y upgrade      > /dev/null
sudo lxc exec ${LXD_NAME} -- apt-get -qq -y dist-upgrade > /dev/null
sudo lxc exec ${LXD_NAME} -- apt-get -qq -y autoremove   > /dev/null

showMessage "Install basic packages"
sudo lxc exec ${LXD_NAME} -- apt-get -qq -y install sudo ssh inetutils-ping curl vim aptitude ca-certificates bash-completion file iproute less lsof moreutils patch rsync net-tools screen ssl-cert strace tcpdump telnet unzip ntp acpid iotop dstat apt-transport-https tar wget openssh-server > /dev/null

showMessage "Configure SSH"
sudo lxc exec ${LXD_NAME} -- sed -i "s/#Port 22/Port 22/g" /etc/ssh/sshd_config
sudo lxc exec ${LXD_NAME} -- sed -i "s/#PermitRootLogin/PermitRootLogin/g" /etc/ssh/sshd_config
sudo lxc exec ${LXD_NAME} -- systemctl restart ssh.service
sudo lxc exec ${LXD_NAME} -- mkdir -p /root/.ssh
sudo lxc file push ~/.ssh/id_rsa.pub ${LXD_NAME}/root/.ssh/authorized_keys
sudo lxc exec ${LXD_NAME} -- chmod 700 /root/.ssh
sudo lxc exec ${LXD_NAME} -- chmod 600 /root/.ssh/authorized_keys
sudo lxc exec ${LXD_NAME} -- chown -R root.root /root/.ssh

showMessage "Add to KnowHost"
if ! ssh-keygen -F ${LXD_HOST} > /dev/null ; then
    ssh-keyscan ${LXD_HOST} 2> /dev/null >>  ~/.ssh/known_hosts
fi
if ! ssh-keygen -F ${LXD_IP} > /dev/null ; then
    ssh-keyscan ${LXD_IP} 2> /dev/null >>  ~/.ssh/known_hosts
fi

showMessage "Test Ping"
ping -c 3 ${LXD_HOST} > /dev/null

showMessage "Test SSH"
ssh root@${LXD_HOST} "ls -lah" > /dev/null

showMessage "Container List"
sudo lxc list

showMessage "Finished"

