#!/bin/bash

showMessage " > Add entry in /etc/hosts"
LXD_IP=`sudo lxc list $LXD_NAME --format csv -c 4 | cut -d' ' -f1`
sudo sh -c "echo \"$LXD_IP $LXD_HOST # Generated by lxd-deploy\" >> /etc/hosts"
sudo lxc exec $LXD_NAME -- sh -c "echo \"127.0.0.1 $LXD_HOST # Generated by lxd-deploy\" >> /etc/hosts"
