#!/bin/bash

showMessage " > Add entries in /etc/hosts"

for LXD_HOST in ${LXD_HOSTS[@]}; do
    showMessage "  - $LXD_HOST"
    sudo sh -c "echo \"$LXD_IP $LXD_HOST # Generated by lxd-deploy\" >> /etc/hosts"
    sudo lxc exec $LXD_NAME -- sh -c "echo \"127.0.0.1 $LXD_HOST # Generated by lxd-deploy\" >> /etc/hosts"
done
